name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v2
      with:
        version: 'v1.24.0'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker images (optional)
      run: |
        docker build -t my-database-image ./path-to-database-dockerfile
        docker build -t my-nginx-image ./path-to-nginx-dockerfile
        docker push my-database-image
        docker push my-nginx-image

    - name: Configure kubectl
      run: |
        kubectl config set-cluster my-cluster --server=https://your-cluster-server
        kubectl config set-context my-context --cluster=my-cluster
        kubectl config use-context my-context

    - name: Deploy database and nginx to Kubernetes
      run: |
        kubectl apply -f ./path-to/base-database.yml
        kubectl apply -f ./path-to/nginx-server.yml
