name: Kubernetes Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Kubernetes (kind)
      uses: helm/kind-action@v1.8.0

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.0'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker images
      run: |
        docker build -t my-database-image -f ./docker/Dockerfile-db ./docker
        docker build -t my-nginx-image -f ./docker/Dockerfile-nginx ./docker

    - name: Load Docker images into kind cluster
      run: |
        kind load docker-image my-database-image
        kind load docker-image my-nginx-image

    - name: Deploy database and nginx to Kubernetes
      run: |
        kubectl apply -f ./kubernetes/base-database.yml
        kubectl apply -f ./kubernetes/nginx-server.yml

